"use client";

import Image from "next/image";
import Link from "next/link";
import { Trash2 } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { relativeTime } from "@/lib/community-ui";
import { toast } from "sonner";

type Comment = { id: string; content: string; createdAt: string; userId: string; isOwn: boolean; user: { id: string; name: string | null; username: string; image: string | null } };
export function WorkoutComments({ workoutId, trigger }: { workoutId: number; trigger: ReactNode }) {
  const [open, setOpen] = useState(false); const [comments, setComments] = useState<Comment[]>([]); const [cursor, setCursor] = useState<string | null>(null); const [value, setValue] = useState(""); const [loading, setLoading] = useState(false); const [sending, setSending] = useState(false);
  async function load(next?: string) { setLoading(true); try { const response = await fetch(`/api/workouts/${workoutId}/comments${next ? `?cursor=${encodeURIComponent(next)}` : ""}`); const data = await response.json() as { comments?: Comment[]; nextCursor?: string | null; error?: string }; if (!response.ok) throw new Error(data.error ?? "Unable to load comments."); setComments((current) => next ? [...current, ...(data.comments ?? [])] : data.comments ?? []); setCursor(data.nextCursor ?? null); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load comments."); } finally { setLoading(false); } }
  async function submit() { if (!value.trim() || sending) return; setSending(true); try { const response = await fetch(`/api/workouts/${workoutId}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: value }) }); const data = await response.json() as { comment?: Comment; error?: string }; if (!response.ok || !data.comment) throw new Error(data.error ?? "Unable to comment."); setComments((current) => [data.comment!, ...current]); setValue(""); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to comment."); } finally { setSending(false); } }
  async function remove(commentId: string) { try { const response = await fetch(`/api/workouts/${workoutId}/comments/${commentId}`, { method: "DELETE" }); if (!response.ok) throw new Error("Unable to delete comment."); setComments((current) => current.filter((comment) => comment.id !== commentId)); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to delete comment."); } }
  return <Dialog open={open} onOpenChange={(nextOpen) => { setOpen(nextOpen); if (nextOpen) void load(); }}><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent className="flex h-[min(85dvh,42rem)] max-h-[calc(100dvh-1rem)] flex-col gap-0 p-0 sm:max-w-lg"><DialogHeader className="shrink-0 border-b p-4"><DialogTitle>Comments</DialogTitle><DialogDescription>Share encouragement and training tips.</DialogDescription></DialogHeader><div className="min-h-0 flex-1 overflow-y-auto p-4">{comments.map((comment) => <article key={comment.id} className="mb-3 flex gap-3"><Link href={`/users/${comment.user.id}`}><>{comment.user.image ? <Image src={comment.user.image} alt="" width={36} height={36} unoptimized className="size-9 rounded-full object-cover" /> : <span className="flex size-9 items-center justify-center rounded-full bg-muted text-xs font-bold">{(comment.user.name ?? "U").slice(0, 1)}</span>}</></Link><div className="min-w-0 flex-1 rounded-xl bg-muted/60 px-3 py-2"><p className="text-sm font-medium">{comment.user.name ?? "Calistheni athlete"} <span className="font-normal text-muted-foreground">{comment.user.username} · {relativeTime(new Date(comment.createdAt))}</span></p><p className="break-words text-sm">{comment.content}</p></div>{comment.isOwn ? <Button type="button" size="icon-sm" variant="ghost" aria-label="Delete your comment" onClick={() => void remove(comment.id)}><Trash2 /></Button> : null}</article>)}{loading ? <p className="text-sm text-muted-foreground">Loading comments…</p> : null}{!loading && !comments.length ? <p className="text-sm text-muted-foreground">Be the first to comment.</p> : null}{cursor ? <Button type="button" variant="ghost" className="w-full" disabled={loading} onClick={() => void load(cursor)}>Load older comments</Button> : null}</div><form className="flex shrink-0 gap-2 border-t p-3" onSubmit={(event) => { event.preventDefault(); void submit(); }}><Textarea value={value} onChange={(event) => setValue(event.target.value)} maxLength={500} placeholder="Add a comment…" aria-label="Comment text" className="min-h-11" /><Button type="submit" disabled={!value.trim() || sending}>{sending ? "Posting…" : "Post"}</Button></form></DialogContent></Dialog>;
}
