"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import { Barcode, Camera, ImagePlus, ListPlus, Loader2, Plus, Search, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { FoodVisual } from "@/components/nutrition/FoodVisual";
import { compressWorkoutPhoto } from "@/lib/workout-photo-client";

export type QuickMeal = "BREAKFAST" | "LUNCH" | "DINNER" | "SNACKS";
type Food = { id?: string; provider?: "USDA" | "OPEN_FOOD_FACTS"; externalId: string; name: string; brandName?: string | null; imageUrl?: string | null; genericIcon?: { url: string } | null; nutritionPer100g: Record<string, number | undefined>; servings?: Array<{ name: string; quantity: number; grams: number; householdUnit?: string | null }> };
type DraftItem = { key: string; food: Food & { id: string }; grams: number; quantity: number; unit: string; confidence?: number };
type Entry = Record<string, unknown>;
const mealLabel = (meal: QuickMeal) => meal.charAt(0) + meal.slice(1).toLowerCase();
const number = (value: unknown) => typeof value === "number" && Number.isFinite(value) ? value : 0;
const macrosFor = (food: Food, grams: number) => ({ calories: number(food.nutritionPer100g.caloriesKcal) * grams / 100, protein: number(food.nutritionPer100g.proteinGrams) * grams / 100, carbs: number(food.nutritionPer100g.carbohydrateGrams) * grams / 100, fat: number(food.nutritionPer100g.fatGrams) * grams / 100 });
const format = (value: number) => Number.isInteger(value) ? String(value) : value.toFixed(1);

async function responseMessage(response: Response, fallback: string) { const body = await response.json().catch(() => null); return body?.error?.message ?? body?.error ?? fallback; }
async function importFood(food: Food): Promise<Food & { id: string }> {
  if (food.id) return food as Food & { id: string };
  if (!food.provider) throw new Error("This food cannot be logged yet.");
  const response = await fetch("/api/nutrition/foods/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider: food.provider, externalId: food.externalId }) });
  if (!response.ok) throw new Error(await responseMessage(response, "Unable to save this food."));
  const imported = (await response.json()).food as Food & { id: string };
  return { ...food, ...imported, servings: imported.servings ?? food.servings };
}
async function searchCanonical(query: string) {
  const response = await fetch(`/api/nutrition/foods/search?q=${encodeURIComponent(query)}`); if (!response.ok) return [] as Food[];
  const data = await response.json(); return [...(data.genericResults ?? []), ...(data.localResults ?? []), ...(data.packagedResults ?? [])] as Food[];
}
async function batchLog(meal: QuickMeal, date: string, items: DraftItem[]) {
  const response = await fetch("/api/nutrition/entries/batch", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ date, mealCategory: meal, items: items.map((item) => ({ foodId: item.food.id, gramsConsumed: item.grams * item.quantity, quantity: item.quantity, unit: item.unit })) }) });
  if (!response.ok) throw new Error(await responseMessage(response, "Unable to add foods.")); return (await response.json()).entries as Entry[];
}

type BarcodeDetectorLike = new (options: { formats: string[] }) => { detect(source: ImageBitmap): Promise<Array<{ rawValue: string }>> };
export async function detectBarcodesFromImage(file: File) {
  const Detector = (globalThis as unknown as { BarcodeDetector?: BarcodeDetectorLike }).BarcodeDetector;
  if (Detector) {
    const bitmap = await createImageBitmap(file, { imageOrientation: "from-image" });
    try { return [...new Set((await new Detector({ formats: ["ean_13", "ean_8", "upc_a", "upc_e"] }).detect(bitmap)).map((result) => result.rawValue).filter((value) => /^\d{8,14}$/.test(value)))]; }
    finally { bitmap.close(); }
  }
  const { BrowserMultiFormatReader } = await import("@zxing/browser"); const url = URL.createObjectURL(file);
  try { const result = await new BrowserMultiFormatReader().decodeFromImageUrl(url); return /^\d{8,14}$/.test(result.getText()) ? [result.getText()] : []; }
  catch { return []; } finally { URL.revokeObjectURL(url); }
}

export function NutritionQuickActions({ meal, date, onEntries }: { meal: QuickMeal; date: string; onEntries: (entries: Entry[]) => void }) {
  const [workflow, setWorkflow] = useState<"barcode" | "ai" | "describe" | null>(null);
  return <>
    <div className="grid grid-cols-3 gap-2">
      <Button variant="outline" size="sm" onClick={() => setWorkflow("barcode")}><Barcode />Barcode</Button>
      <Button variant="outline" size="sm" onClick={() => setWorkflow("ai")}><Camera />AI Scan</Button>
      <Button variant="outline" size="sm" onClick={() => setWorkflow("describe")}><ListPlus />Describe</Button>
    </div>
    <BarcodeWorkflow open={workflow === "barcode"} meal={meal} date={date} close={() => setWorkflow(null)} onEntries={onEntries} />
    <AiWorkflow open={workflow === "ai"} meal={meal} date={date} close={() => setWorkflow(null)} onEntries={onEntries} />
    <DescribeWorkflow open={workflow === "describe"} meal={meal} date={date} close={() => setWorkflow(null)} onEntries={onEntries} />
  </>;
}

function BarcodeWorkflow({ open, meal, date, close, onEntries }: { open: boolean; meal: QuickMeal; date: string; close: () => void; onEntries: (entries: Entry[]) => void }) {
  const [code, setCode] = useState(""); const [detected, setDetected] = useState<string[]>([]); const [food, setFood] = useState<(Food & { id: string }) | null>(null); const [grams, setGrams] = useState(100); const [quantity, setQuantity] = useState(1); const [unit, setUnit] = useState("g"); const [busy, setBusy] = useState(false); const [phase, setPhase] = useState<"reading" | "looking" | null>(null); const [error, setError] = useState("");
  function reset() { setCode(""); setDetected([]); setFood(null); setGrams(100); setQuantity(1); setUnit("g"); setBusy(false); setPhase(null); setError(""); }
  function dismiss() { reset(); close(); }
  async function lookup(value: string) { const barcode = value.replaceAll(/\s/g, ""); if (!/^\d{8,14}$/.test(barcode)) return setError("Enter a valid 8–14 digit UPC, EAN, or GTIN."); setBusy(true); setPhase("looking"); setError(""); try { const response = await fetch(`/api/nutrition/foods/barcode/${barcode}`); if (!response.ok) throw new Error(response.status === 404 ? "We couldn't find a food for this barcode." : await responseMessage(response, "Barcode lookup failed.")); const data = await response.json(); const match = await importFood(data.local ?? data.external); setFood(match); const defaultServing = match.servings?.[0]; setGrams(defaultServing?.grams ?? 100); setQuantity(1); setUnit(defaultServing?.name.slice(0, 40) ?? "g"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Barcode lookup failed."); } finally { setBusy(false); setPhase(null); } }
  async function photo(file?: File) { if (!file) return; setBusy(true); setPhase("reading"); setError(""); try { const values = await detectBarcodesFromImage(file); setDetected(values); if (values.length === 1) { setCode(values[0]); await lookup(values[0]); } else if (!values.length) setError("No supported barcode was detected. Try another photo or enter it manually."); } catch { setError("The barcode image could not be read."); } finally { setBusy(false); setPhase(null); } }
  async function add() { if (!food || grams <= 0 || quantity <= 0 || busy) return; setBusy(true); try { const entries = await batchLog(meal, date, [{ key: food.id, food, grams, quantity, unit }]); onEntries(entries); dismiss(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to add product."); setBusy(false); } }
  return <Sheet open={open} onOpenChange={(value) => !value && dismiss()}><SheetContent side="bottom" className="h-[92dvh] overflow-y-auto"><SheetHeader><SheetTitle>Barcode</SheetTitle><SheetDescription>Scan a barcode from a photo or enter the number manually.</SheetDescription></SheetHeader><div className="space-y-4 p-4"><Tabs defaultValue="photo"><TabsList><TabsTrigger value="photo">Scan / Photo</TabsTrigger><TabsTrigger value="manual">Enter manually</TabsTrigger></TabsList><TabsContent value="photo"><div className="grid grid-cols-2 gap-2"><Button asChild variant="outline"><Label className="cursor-pointer justify-center"><Camera />Take photo<Input disabled={busy} className="sr-only" type="file" accept="image/*" capture="environment" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; void photo(file); }} /></Label></Button><Button asChild variant="outline"><Label className="cursor-pointer justify-center"><ImagePlus />Choose photo<Input disabled={busy} className="sr-only" type="file" accept="image/*" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; void photo(file); }} /></Label></Button></div>{phase === "reading" ? <p className="mt-3 text-sm text-muted-foreground">Reading barcode…</p> : phase === "looking" ? <p className="mt-3 text-sm text-muted-foreground">Looking up food…</p> : null}{detected.length > 1 ? <div className="mt-3"><p className="text-sm font-medium">Choose a detected barcode</p><div className="mt-2 flex flex-wrap gap-2">{detected.map((value) => <Button key={value} size="sm" variant="outline" disabled={busy} onClick={() => { setCode(value); void lookup(value); }}>{value}</Button>)}</div></div> : null}</TabsContent><TabsContent value="manual"><Label htmlFor="manual-barcode">Barcode number</Label><div className="mt-1 flex gap-2"><Input id="manual-barcode" inputMode="numeric" pattern="[0-9]*" value={code} onChange={(event) => setCode(event.target.value.replaceAll(/\D/g, ""))} placeholder="3017620422003" /><Button disabled={busy} onClick={() => void lookup(code)}>{busy ? <Loader2 className="animate-spin" /> : <Search />}Lookup</Button></div>{phase === "looking" ? <p className="mt-2 text-sm text-muted-foreground">Looking up food…</p> : null}</TabsContent></Tabs>{error ? <><Alert><AlertTitle>Barcode unavailable</AlertTitle><AlertDescription>{error}</AlertDescription></Alert><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={reset}>Try another barcode</Button><Button size="sm" variant="ghost" onClick={dismiss}>Search foods</Button></div></> : null}{food ? <><FoodAmountCard food={food} grams={grams} setGrams={setGrams} quantity={quantity} setQuantity={setQuantity} unit={unit} setUnit={setUnit} /><Button className="w-full" disabled={busy} onClick={() => void add()}>Add to {mealLabel(meal)}</Button></> : null}</div></SheetContent></Sheet>;
}

function FoodAmountCard({ food, grams, setGrams, quantity = 1, setQuantity, unit = "g", setUnit, remove, replace, confidence }: { food: Food; grams: number; setGrams: (value: number) => void; quantity?: number; setQuantity?: (value: number) => void; unit?: string; setUnit?: (value: string) => void; remove?: () => void; replace?: () => void; confidence?: number }) {
  const macro = macrosFor(food, grams * quantity);
  return <Card><CardContent className="p-3"><div className="flex min-w-0 items-center gap-3"><FoodVisual imageUrl={food.imageUrl} iconPath={food.genericIcon?.url} name={food.name} size="sm" /><div className="min-w-0 flex-1"><p className="line-clamp-2 font-medium">{food.name}</p>{food.brandName ? <p className="truncate text-xs text-muted-foreground">{food.brandName}</p> : null}{confidence !== undefined && confidence < .6 ? <p className="text-xs text-amber-600">Low-confidence match — review carefully</p> : null}</div>{replace ? <Button size="sm" variant="ghost" onClick={replace}>Replace</Button> : null}{remove ? <Button size="icon-sm" variant="ghost" aria-label={`Remove ${food.name}`} onClick={remove}><Trash2 /></Button> : null}</div>{food.servings?.length && setUnit ? <Label className="mt-3 block">Serving<select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={unit} onChange={(event) => { const nextUnit = event.target.value; setUnit(nextUnit); const serving = food.servings?.find((candidate) => candidate.name.slice(0, 40) === nextUnit); if (serving) setGrams(serving.grams); }}><option value="g">Custom grams</option>{food.servings.map((serving) => <option key={`${serving.name}:${serving.grams}`} value={serving.name.slice(0, 40)}>{serving.name} · {format(serving.grams)} g</option>)}</select></Label> : null}<div className="mt-3 grid grid-cols-2 gap-3"><Label>Amount (g)<Input type="number" min="1" max="10000" value={grams} onChange={(event) => { setGrams(Number(event.target.value)); setUnit?.("g"); }} /></Label>{setQuantity ? <Label>Quantity<Input type="number" min="0.1" max="100" step="0.1" value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} /></Label> : null}</div><p className="mt-2 text-xs text-muted-foreground">{format(macro.calories)} kcal · P {format(macro.protein)} · C {format(macro.carbs)} · F {format(macro.fat)}</p></CardContent></Card>;
}

function AiWorkflow({ open, meal, date, close, onEntries }: { open: boolean; meal: QuickMeal; date: string; close: () => void; onEntries: (entries: Entry[]) => void }) {
  const [image, setImage] = useState<File | null>(null); const [preview, setPreview] = useState<string | null>(null); const [description, setDescription] = useState(""); const [items, setItems] = useState<DraftItem[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  function chooseImage(file?: File) { if (!file) return; if (preview) URL.revokeObjectURL(preview); setImage(file); setPreview(URL.createObjectURL(file)); setItems([]); setError(""); }
  function clearImage() { if (preview) URL.revokeObjectURL(preview); setImage(null); setPreview(null); setItems([]); setError(""); }
  function reset() { if (preview) URL.revokeObjectURL(preview); setImage(null); setPreview(null); setDescription(""); setItems([]); setBusy(false); setError(""); }
  function dismiss() { reset(); close(); }
  async function analyze() { if (!image || busy) return setError("Take or choose a food photo first."); setBusy(true); setError(""); try { const compressed = await compressWorkoutPhoto(image); if (compressed.size > 4 * 1024 * 1024) throw new Error("The compressed image is still larger than 4 MB."); const form = new FormData(); form.set("image", compressed); form.set("description", description); const response = await fetch("/api/nutrition/ai-scan", { method: "POST", body: form }); if (!response.ok) throw new Error(await responseMessage(response, "AI food scan failed.")); const result = await response.json(); const resolved: DraftItem[] = []; const unresolved: string[] = []; for (const detected of result.foods) { const matches = await searchCanonical(detected.label); if (!matches.length) { unresolved.push(detected.label); continue; } try { const food = await importFood(matches[0]); resolved.push({ key: crypto.randomUUID(), food, grams: detected.estimatedGrams, quantity: 1, unit: "g", confidence: detected.confidence }); } catch { unresolved.push(detected.label); } } setItems(resolved); if (unresolved.length) setError(`Choose matching foods manually for: ${unresolved.join(", ")}.`); if (!resolved.length && !unresolved.length) setError("No foods were detected. Try another photo or add foods manually."); } catch (reason) { setError(reason instanceof Error ? reason.message : "AI food scan failed."); } finally { setBusy(false); } }
  async function confirm() { if (!items.length || busy) return setError("Add at least one reviewed food."); setBusy(true); try { onEntries(await batchLog(meal, date, items)); dismiss(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to add scanned foods."); setBusy(false); } }
  return <Sheet open={open} onOpenChange={(value) => !value && dismiss()}><SheetContent side="bottom" className="h-[94dvh] overflow-y-auto"><SheetHeader><SheetTitle>AI food scan</SheetTitle><SheetDescription>Take or choose a photo of your food. You can add an optional description to improve the estimate.</SheetDescription></SheetHeader><div className="space-y-4 p-4"><Alert><Camera /><AlertTitle>Photo privacy</AlertTitle><AlertDescription>Your photo is sent securely for food recognition and is not saved to your Calistheni profile. AI estimates can be inaccurate; review foods and portions before adding them.</AlertDescription></Alert>{preview ? <div className="relative h-64 overflow-hidden rounded-xl bg-muted"><Image src={preview} alt="Selected meal" fill unoptimized className="object-contain" /><Button className="absolute right-2 top-2" size="icon-sm" variant="secondary" aria-label="Remove image" onClick={clearImage}><X /></Button></div> : <div className="grid grid-cols-2 gap-2"><Button asChild variant="outline"><Label className="cursor-pointer justify-center"><Camera />Take photo<Input className="sr-only" type="file" accept="image/*" capture="environment" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; chooseImage(file); }} /></Label></Button><Button asChild variant="outline"><Label className="cursor-pointer justify-center"><ImagePlus />Choose photo<Input className="sr-only" type="file" accept="image/*" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; chooseImage(file); }} /></Label></Button></div>}<Label htmlFor="ai-description">Description (optional)</Label><Input id="ai-description" value={description} maxLength={200} onChange={(event) => setDescription(event.target.value)} placeholder="e.g. 2 eggs, toast and half an avocado" /><Button className="w-full" disabled={!image || busy} onClick={() => void analyze()}>{busy ? <Loader2 className="animate-spin" /> : <Camera />}{busy ? "Analyzing meal…" : "Analyze meal"}</Button>{error ? <Alert><AlertTitle>Review needed</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> : null}{items.length ? <ReviewList items={items} setItems={setItems} /> : null}<DraftSearch onFood={(food) => setItems((current) => [...current, { key: crypto.randomUUID(), food, grams: 100, quantity: 1, unit: "g" }])} />{items.length ? <><MealTotal items={items} /><Button className="w-full" disabled={busy} onClick={() => void confirm()}>Add {items.length} {items.length === 1 ? "food" : "foods"} to {mealLabel(meal)}</Button></> : null}</div></SheetContent></Sheet>;
}

function DescribeWorkflow({ open, meal, date, close, onEntries }: { open: boolean; meal: QuickMeal; date: string; close: () => void; onEntries: (entries: Entry[]) => void }) {
  const [items, setItems] = useState<DraftItem[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  function dismiss() { setItems([]); setBusy(false); setError(""); close(); }
  async function confirm() { if (!items.length || busy) return setError("Add at least one food."); setBusy(true); try { onEntries(await batchLog(meal, date, items)); dismiss(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to add meal."); setBusy(false); } }
  return <Sheet open={open} onOpenChange={(value) => !value && dismiss()}><SheetContent side="bottom" className="h-[94dvh] overflow-y-auto"><SheetHeader><SheetTitle>Describe meal</SheetTitle><SheetDescription>Build your meal manually by selecting each food and amount.</SheetDescription></SheetHeader><div className="space-y-4 p-4"><DraftSearch onFood={(food) => setItems((current) => [...current, { key: crypto.randomUUID(), food, grams: 100, quantity: 1, unit: "g" }])} />{items.length ? <ReviewList items={items} setItems={setItems} /> : <p className="rounded-lg border border-dashed p-5 text-center text-sm text-muted-foreground">No foods selected yet.</p>}{error ? <Alert><AlertTitle>Meal not added</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> : null}{items.length ? <><MealTotal items={items} /><Button className="w-full" disabled={busy} onClick={() => void confirm()}>{busy ? <Loader2 className="animate-spin" /> : null}Add {items.length} {items.length === 1 ? "food" : "foods"} to {mealLabel(meal)}</Button></> : null}</div></SheetContent></Sheet>;
}

function DraftSearch({ onFood }: { onFood: (food: Food & { id: string }) => void }) {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<Food[]>([]); const [busy, setBusy] = useState(false); const request = useRef(0);
  async function search() { if (query.trim().length < 2 || busy) return; const id = ++request.current; setBusy(true); const matches = await searchCanonical(query.trim()); if (id === request.current) { setResults(matches); setBusy(false); } }
  async function select(food: Food) { setBusy(true); try { onFood(await importFood(food)); setQuery(""); setResults([]); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "Unable to select food."); } finally { setBusy(false); } }
  return <div><Label htmlFor="draft-food-search">Add food</Label><div className="mt-1 flex gap-2"><Input id="draft-food-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search foods" onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); void search(); } }} /><Button variant="outline" disabled={busy || query.trim().length < 2} onClick={() => void search()}>{busy ? <Loader2 className="animate-spin" /> : <Plus />}</Button></div>{results.length ? <div className="mt-2 max-h-52 space-y-1 overflow-y-auto rounded-lg border p-1">{results.slice(0, 10).map((food) => <button key={`${food.id ? "local" : food.provider}:${food.id ?? food.externalId}`} className="flex w-full min-w-0 items-center gap-2 rounded-md p-2 text-left hover:bg-muted" onClick={() => void select(food)}><FoodVisual imageUrl={food.imageUrl} iconPath={food.genericIcon?.url} name={food.name} size="sm" /><span className="line-clamp-2 min-w-0 text-sm font-medium">{food.name}</span></button>)}</div> : null}</div>;
}
function ReviewList({ items, setItems }: { items: DraftItem[]; setItems: (items: DraftItem[] | ((items: DraftItem[]) => DraftItem[])) => void }) { const [replaceKey, setReplaceKey] = useState<string | null>(null); return <div className="space-y-2">{items.map((item) => <div key={item.key}><FoodAmountCard food={item.food} grams={item.grams} quantity={item.quantity} unit={item.unit} confidence={item.confidence} setGrams={(grams) => setItems((current) => current.map((candidate) => candidate.key === item.key ? { ...candidate, grams } : candidate))} setQuantity={(quantity) => setItems((current) => current.map((candidate) => candidate.key === item.key ? { ...candidate, quantity } : candidate))} setUnit={(unit) => setItems((current) => current.map((candidate) => candidate.key === item.key ? { ...candidate, unit } : candidate))} replace={() => setReplaceKey(item.key)} remove={() => setItems((current) => current.filter((candidate) => candidate.key !== item.key))} />{replaceKey === item.key ? <div className="mt-2 rounded-lg border p-2"><DraftSearch onFood={(food) => { setItems((current) => current.map((candidate) => candidate.key === item.key ? { ...candidate, food, grams: 100, quantity: 1, unit: "g", confidence: undefined } : candidate)); setReplaceKey(null); }} /></div> : null}</div>)}</div>; }
function MealTotal({ items }: { items: DraftItem[] }) { const total = useMemo(() => items.reduce((sum, item) => { const macro = macrosFor(item.food, item.grams * item.quantity); return { calories: sum.calories + macro.calories, protein: sum.protein + macro.protein, carbs: sum.carbs + macro.carbs, fat: sum.fat + macro.fat }; }, { calories: 0, protein: 0, carbs: 0, fat: 0 }), [items]); return <Card><CardContent className="p-3"><p className="font-medium">Meal total</p><p className="text-sm text-muted-foreground">{format(total.calories)} kcal · P {format(total.protein)} · C {format(total.carbs)} · F {format(total.fat)}</p></CardContent></Card>; }
