import { FoodDataValueSource, FoodFreshnessStatus, FoodImportStatus, FoodRevisionReason, FoodSource, FoodType, FoodVerificationStatus, Prisma } from "@/lib/generated/prisma/client";
import { prisma } from "@/lib/prisma";
import { isMaterialFoodChange, normalizeFoodQuery } from "./normalization";
import { getOpenFoodFactsProduct, searchOpenFoodFactsFoods } from "./providers/open-food-facts";
import { ProviderError } from "./providers/http";
import { getUsdaFood, searchUsdaFoods } from "./providers/usda";
import type { ExternalFoodResult, FoodSearchResponse, FoodSummary, NutritionValues, ProviderState } from "./types";

const providerFor = (provider: ExternalFoodResult["provider"]) => provider === "USDA" ? FoodSource.USDA : FoodSource.OPEN_FOOD_FACTS;
const daysFor = (food: { source: FoodSource; type: FoodType; importStatus: FoodImportStatus }) => food.importStatus === FoodImportStatus.INCOMPLETE ? 7 : food.source === FoodSource.OPEN_FOOD_FACTS ? Number(process.env.OPEN_FOOD_FACTS_REVALIDATE_DAYS ?? 30) : food.type === FoodType.BRANDED ? 60 : Number(process.env.USDA_REVALIDATE_DAYS ?? 180);
const nextDate = (food: { source: FoodSource; type: FoodType; importStatus: FoodImportStatus }, from = new Date()) => new Date(from.getTime() + daysFor(food) * 86400000);
const numeric = (value: unknown) => value === null || value === undefined ? undefined : Number(value);
function nutritionFromRecord(food: Record<string, unknown>): NutritionValues { return { caloriesKcal: numeric(food.caloriesKcal), proteinGrams: numeric(food.proteinGrams), carbohydrateGrams: numeric(food.carbohydrateGrams), fatGrams: numeric(food.fatGrams), fiberGrams: numeric(food.fiberGrams), sugarGrams: numeric(food.sugarGrams), saturatedFatGrams: numeric(food.saturatedFatGrams), transFatGrams: numeric(food.transFatGrams), addedSugarGrams: numeric(food.addedSugarGrams), sodiumMg: numeric(food.sodiumMg), saltGrams: numeric(food.saltGrams), cholesterolMg: numeric(food.cholesterolMg), potassiumMg: numeric(food.potassiumMg), calciumMg: numeric(food.calciumMg), ironMg: numeric(food.ironMg) }; }
export function toFoodSummary(food: Record<string, unknown>): FoodSummary { const next = food.nextRevalidateAt instanceof Date ? food.nextRevalidateAt : null; return { id: String(food.id), name: String(food.name), brandName: food.brandName ? String(food.brandName) : null, barcode: food.barcode ? String(food.barcode) : null, imageUrl: food.imageUrl ? String(food.imageUrl) : null, type: String(food.type), source: String(food.source), sourceExternalId: String(food.sourceExternalId), verificationStatus: String(food.verificationStatus), freshnessStatus: String(food.freshnessStatus), confidenceScore: Number(food.confidenceScore), nutritionPer100g: nutritionFromRecord(food), importedAt: (food.importedAt as Date).toISOString(), lastRevalidatedAt: food.lastRevalidatedAt ? (food.lastRevalidatedAt as Date).toISOString() : null, nextRevalidateAt: next?.toISOString() ?? null, currentRevisionId: food.currentRevisionId ? String(food.currentRevisionId) : null, isLocal: true, revalidationRecommended: !next || next <= new Date() }; }
export async function searchFoods(query: string): Promise<FoodSearchResponse> {
  const normalized = normalizeFoodQuery(query); const local = await prisma.food.findMany({ where: { OR: [{ normalizedName: { contains: normalized } }, { name: { contains: query, mode: "insensitive" } }, { brandName: { contains: query, mode: "insensitive" } }, { aliases: { some: { normalizedName: { contains: normalized } } } }] }, orderBy: [{ selectionCount: "desc" }, { updatedAt: "desc" }], take: 12 });
  const localResults = local.map((food) => toFoodSummary(food)); const strong = localResults.filter((food) => food.name.toLocaleLowerCase() === normalized || food.name.toLocaleLowerCase().startsWith(normalized));
  if (strong.length >= 5) return { query, localResults, externalResults: [], providers: { usda: { attempted: false, available: Boolean(process.env.USDA_FDC_API_KEY), error: null }, openFoodFacts: { attempted: false, available: true, error: null } } };
  const [usda, off] = await Promise.allSettled([searchUsdaFoods(query), searchOpenFoodFactsFoods(query)]);
  const state = (result: PromiseSettledResult<ExternalFoodResult[]>, configured = true): ProviderState => {
    if (result.status === "fulfilled") return { attempted: true, available: true, error: null };
    const code = result.reason instanceof ProviderError ? result.reason.code : "UNAVAILABLE";
    return {
      attempted: true,
      available: configured,
      error: code === "TIMEOUT" || code === "RATE_LIMITED" ? code : "UNAVAILABLE",
    };
  };
  return { query, localResults, externalResults: [...(usda.status === "fulfilled" ? usda.value : []), ...(off.status === "fulfilled" ? off.value : [])], providers: { usda: state(usda, Boolean(process.env.USDA_FDC_API_KEY)), openFoodFacts: state(off) } };
}
async function fetchExternal(provider: "USDA" | "OPEN_FOOD_FACTS", externalId: string) { return provider === "USDA" ? getUsdaFood(externalId) : getOpenFoodFactsProduct(externalId); }
const nutritionFields = ["caloriesKcal", "proteinGrams", "carbohydrateGrams", "fatGrams", "fiberGrams", "sugarGrams", "saturatedFatGrams", "transFatGrams", "addedSugarGrams", "sodiumMg", "saltGrams", "cholesterolMg", "potassiumMg", "calciumMg", "ironMg"] as const;
function persistenceFood(result: ExternalFoodResult) { return { type: result.foodType === "GENERIC" ? FoodType.GENERIC : FoodType.BRANDED, name: result.name, normalizedName: normalizeFoodQuery(result.name), description: result.description ?? null, brandName: result.brandName ?? null, barcode: result.barcode ?? null, imageUrl: result.imageUrl ?? null, languageCode: result.languageCode ?? null, countryCodes: result.countryCodes, nutritionBasisGrams: 100, ...result.nutritionPer100g, calorieValueSource: FoodDataValueSource.PROVIDER, source: providerFor(result.provider), sourceExternalId: result.externalId, sourceUpdatedAt: result.sourceUpdatedAt ?? null, verificationStatus: result.verificationStatus === "OFFICIAL_SOURCE" ? FoodVerificationStatus.OFFICIAL_SOURCE : result.verificationStatus === "COMMUNITY_SOURCE" ? FoodVerificationStatus.COMMUNITY_SOURCE : FoodVerificationStatus.UNVERIFIED, importStatus: result.isComplete ? FoodImportStatus.ACTIVE : FoodImportStatus.INCOMPLETE, freshnessStatus: FoodFreshnessStatus.FRESH, confidenceScore: result.confidenceScore, lastFetchedAt: new Date(), lastRevalidatedAt: new Date(), nextRevalidateAt: nextDate({ source: providerFor(result.provider), type: result.foodType === "GENERIC" ? FoodType.GENERIC : FoodType.BRANDED, importStatus: result.isComplete ? FoodImportStatus.ACTIVE : FoodImportStatus.INCOMPLETE }) }; }
function revisionData(foodId: string, revisionNumber: number, result: ExternalFoodResult, sourceRecordId: string, reason: FoodRevisionReason) { const food = persistenceFood(result); return { foodId, revisionNumber, reason, source: food.source, sourceExternalId: result.externalId, name: result.name, brandName: result.brandName, barcode: result.barcode, imageUrl: result.imageUrl, nutritionBasisGrams: 100, ...result.nutritionPer100g, confidenceScore: result.confidenceScore, verificationStatus: food.verificationStatus, sourceUpdatedAt: result.sourceUpdatedAt ?? null, sourceRecordId, normalizedDataChecksum: result.checksum }; }
async function persistProviderDetails(tx: Prisma.TransactionClient, foodId: string, result: ExternalFoodResult, source: FoodSource) {
  if (!result.details) return;
  const details = result.details;
  await tx.foodDetails.upsert({ where: { foodId }, create: { foodId, productImageUrl: details.productImageUrl ?? null, nutritionImageUrl: details.nutritionImageUrl ?? null, ingredientsImageUrl: details.ingredientsImageUrl ?? null, packageQuantityText: details.packageQuantityText ?? null, packageQuantityGrams: details.packageQuantityGrams ?? null, servingSizeText: details.servingSizeText ?? null, defaultServingGrams: details.defaultServingGrams ?? null, categories: details.categories, labels: details.labels, ingredientsText: details.ingredientsText ?? null, allergens: details.allergens, traces: details.traces, additives: details.additives, nutriScoreGrade: details.nutriScoreGrade ?? null, novaGroup: details.novaGroup ?? null, nutrientLevels: details.nutrientLevels ?? Prisma.JsonNull, veganStatus: details.veganStatus ?? null, vegetarianStatus: details.vegetarianStatus ?? null, palmOilStatus: details.palmOilStatus ?? null, providerCreatedAt: details.providerCreatedAt ?? null }, update: { productImageUrl: details.productImageUrl ?? null, nutritionImageUrl: details.nutritionImageUrl ?? null, ingredientsImageUrl: details.ingredientsImageUrl ?? null, packageQuantityText: details.packageQuantityText ?? null, packageQuantityGrams: details.packageQuantityGrams ?? null, servingSizeText: details.servingSizeText ?? null, defaultServingGrams: details.defaultServingGrams ?? null, categories: details.categories, labels: details.labels, ingredientsText: details.ingredientsText ?? null, allergens: details.allergens, traces: details.traces, additives: details.additives, nutriScoreGrade: details.nutriScoreGrade ?? null, novaGroup: details.novaGroup ?? null, nutrientLevels: details.nutrientLevels ?? Prisma.JsonNull, veganStatus: details.veganStatus ?? null, vegetarianStatus: details.vegetarianStatus ?? null, palmOilStatus: details.palmOilStatus ?? null, providerCreatedAt: details.providerCreatedAt ?? null } });
  await tx.foodNutrient.deleteMany({ where: { foodId } });
  if (details.nutrients.length) await tx.foodNutrient.createMany({ data: details.nutrients.map((nutrient) => ({ foodId, ...nutrient, basisGrams: 100, source, sourceExternalId: result.externalId })) });
}
export async function importExternalFood(provider: "USDA" | "OPEN_FOOD_FACTS", externalId: string) {
  const result = await fetchExternal(provider, externalId); const source = providerFor(provider); const existing = await prisma.food.findUnique({ where: { source_sourceExternalId: { source, sourceExternalId: result.externalId } }, select: { id: true } }); if (existing) { await prisma.food.update({ where: { id: existing.id }, data: { selectionCount: { increment: 1 } } }); return prisma.food.findUniqueOrThrow({ where: { id: existing.id } }); }
  try { return await prisma.$transaction(async (tx) => { const food = await tx.food.create({ data: { ...persistenceFood(result), selectionCount: 1 } }); const sourceRecord = await tx.foodSourceRecord.create({ data: { foodId: food.id, source, sourceExternalId: result.externalId, rawData: result.raw as Prisma.InputJsonValue, checksum: result.checksum, sourceUpdatedAt: result.sourceUpdatedAt ?? null, responseStatus: 200 } }); const revision = await tx.foodRevision.create({ data: revisionData(food.id, 1, result, sourceRecord.id, FoodRevisionReason.INITIAL_IMPORT) }); await tx.food.update({ where: { id: food.id }, data: { currentRevisionId: revision.id } }); if (result.servings.length) await tx.foodServing.createMany({ data: result.servings.map((serving, index) => ({ foodId: food.id, name: serving.name, quantity: serving.quantity, grams: serving.grams, householdUnit: serving.householdUnit ?? null, isDefault: index === 0, source, sourceExternalId: serving.sourceExternalId ?? null })) }); await tx.foodAlias.create({ data: { foodId: food.id, name: result.name, normalizedName: normalizeFoodQuery(result.name), languageCode: result.languageCode ?? null, source } }); await persistProviderDetails(tx, food.id, result, source); return tx.food.findUniqueOrThrow({ where: { id: food.id } }); }); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return prisma.food.findUniqueOrThrow({ where: { source_sourceExternalId: { source, sourceExternalId: result.externalId } } }); throw error; }
}

export async function revalidateFood(foodId: string, force = false) {
  const food = await prisma.food.findUnique({ where: { id: foodId }, include: { currentRevision: true } });
  if (!food) return { status: "NOT_FOUND" as const };
  if (!force && food.nextRevalidateAt && food.nextRevalidateAt > new Date()) return { status: "SKIPPED_FRESH" as const, foodId };
  if (food.source !== FoodSource.USDA && food.source !== FoodSource.OPEN_FOOD_FACTS) return { status: "SKIPPED_UNSUPPORTED" as const, foodId };
  const provider = food.source === FoodSource.USDA ? "USDA" : "OPEN_FOOD_FACTS";
  try {
    const incoming = await fetchExternal(provider, food.sourceExternalId);
    const incomingValues = incoming.nutritionPer100g;
    const currentValues = nutritionFromRecord(food as unknown as Record<string, unknown>);
    const completeRegression = food.importStatus === FoodImportStatus.ACTIVE && !incoming.isComplete;
    if (completeRegression) { await prisma.foodSourceRecord.create({ data: { foodId, source: food.source, sourceExternalId: food.sourceExternalId, rawData: incoming.raw as Prisma.InputJsonValue, checksum: incoming.checksum, sourceUpdatedAt: incoming.sourceUpdatedAt ?? null, responseStatus: 200 } }); await prisma.food.update({ where: { id: foodId }, data: { freshnessStatus: FoodFreshnessStatus.PROVIDER_UNAVAILABLE, lastFetchedAt: new Date(), nextRevalidateAt: new Date(Date.now() + 7 * 86400000) } }); return { status: "INCOMPLETE_PROVIDER_DATA" as const, foodId }; }
    const changes = isMaterialFoodChange({ ...currentValues, name: food.name, brandName: food.brandName, barcode: food.barcode }, { ...incomingValues, name: incoming.name, brandName: incoming.brandName, barcode: incoming.barcode });
    return await prisma.$transaction(async (tx) => { const sourceRecord = await tx.foodSourceRecord.create({ data: { foodId, source: food.source, sourceExternalId: food.sourceExternalId, rawData: incoming.raw as Prisma.InputJsonValue, checksum: incoming.checksum, sourceUpdatedAt: incoming.sourceUpdatedAt ?? null, responseStatus: 200 } }); const persisted = persistenceFood(incoming); if (!changes || food.currentRevision?.normalizedDataChecksum === incoming.checksum) { await tx.food.update({ where: { id: foodId }, data: { lastFetchedAt: new Date(), lastRevalidatedAt: new Date(), nextRevalidateAt: nextDate(food), freshnessStatus: FoodFreshnessStatus.FRESH } }); await persistProviderDetails(tx, foodId, incoming, food.source); return { status: "UNCHANGED" as const, foodId, currentRevisionId: food.currentRevisionId }; }
      const revisionNumber = (await tx.foodRevision.aggregate({ where: { foodId }, _max: { revisionNumber: true } }))._max.revisionNumber! + 1;
      const revision = await tx.foodRevision.create({ data: revisionData(foodId, revisionNumber, incoming, sourceRecord.id, force ? FoodRevisionReason.MANUAL_REFRESH : FoodRevisionReason.PROVIDER_UPDATE) }); await tx.food.update({ where: { id: foodId }, data: { ...persisted, currentRevisionId: revision.id, lastFetchedAt: new Date(), lastRevalidatedAt: new Date(), nextRevalidateAt: nextDate(persisted) } }); await persistProviderDetails(tx, foodId, incoming, food.source); return { status: "UPDATED" as const, foodId, previousRevisionId: food.currentRevisionId, currentRevisionId: revision.id, materialChanges: changes ? nutritionFields.filter((field) => currentValues[field] !== incomingValues[field]) : [] }; });
  } catch (error) { const state = error instanceof ProviderError && error.code === "NOT_FOUND" ? FoodFreshnessStatus.SOURCE_REMOVED : FoodFreshnessStatus.PROVIDER_UNAVAILABLE; await prisma.food.update({ where: { id: foodId }, data: { freshnessStatus: state, nextRevalidateAt: new Date(Date.now() + (error instanceof ProviderError && error.code === "RATE_LIMITED" ? 3600000 : 86400000)) } }); return { status: state === FoodFreshnessStatus.SOURCE_REMOVED ? "SOURCE_REMOVED" as const : "UNAVAILABLE" as const, foodId }; }
}
