CREATE TYPE "TrainingStyle" AS ENUM ('CALISTHENICS', 'GYM', 'BOTH');

CREATE TYPE "PrimaryGoal" AS ENUM ('FIND_PARKS', 'TRACK_WORKOUTS', 'BOTH');

ALTER TABLE "User" ADD COLUMN "onboardingCompleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "trainingStyle" "TrainingStyle";
ALTER TABLE "User" ADD COLUMN "primaryGoal" "PrimaryGoal";
ALTER TABLE "User" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE "User" SET "onboardingCompleted" = true;
