import { NextResponse } from "next/server";
import { createInternalServerErrorResponse, createJsonErrorResponse, createJsonValidationErrorResponse } from "@/lib/api-response";
import { createUserUnauthorizedResponse, getAuthenticatedUserId } from "@/lib/user-auth";
import { prisma } from "@/lib/prisma";
import { measurementSchema } from "@/lib/progress";
import { validateStoredMeasurementCapabilities } from "@/lib/progress";
import { getUserSubscription, hasProAccess } from "@/lib/entitlements";
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { const userId = await getAuthenticatedUserId(); if (!userId) return createUserUnauthorizedResponse(); const { id } = await params; let body: unknown; try { body = await request.json(); } catch { return createJsonErrorResponse("Invalid JSON payload.", 400); } const parsed = measurementSchema.partial().safeParse(body); if (!parsed.success) return createJsonValidationErrorResponse("Invalid measurement entry.", parsed.error.flatten().fieldErrors); const capabilityValidation = validateStoredMeasurementCapabilities(parsed.data as Record<string, unknown>, hasProAccess(await getUserSubscription(userId))); if (!capabilityValidation.success) return createJsonValidationErrorResponse("Some measurements require Pro.", Object.fromEntries(Object.entries(capabilityValidation.errors).map(([key, error]) => [key, [error]]))); try { const result = await prisma.bodyMeasurementEntry.updateMany({ where: { id, userId }, data: parsed.data }); return result.count ? NextResponse.json({ ok: true }) : createJsonErrorResponse("Measurement not found.", 404); } catch (error) { console.error(error); return createInternalServerErrorResponse(); } }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { const userId = await getAuthenticatedUserId(); if (!userId) return createUserUnauthorizedResponse(); const { id } = await params; try { const result = await prisma.bodyMeasurementEntry.deleteMany({ where: { id, userId } }); return result.count ? NextResponse.json({ ok: true }) : createJsonErrorResponse("Measurement not found.", 404); } catch (error) { console.error(error); return createInternalServerErrorResponse(); } }
