import { NextResponse } from "next/server";
import { createInternalServerErrorResponse, createJsonErrorResponse, createJsonValidationErrorResponse } from "@/lib/api-response";
import { createUserUnauthorizedResponse, getAuthenticatedUserId } from "@/lib/user-auth";
import { prisma } from "@/lib/prisma";
import { measurementSchema } from "@/lib/progress";
import { validateStoredMeasurementCapabilities } from "@/lib/progress";
import { getUserSubscription, hasProAccess } from "@/lib/entitlements";
import { FREE_MEASUREMENT_HISTORY_LIMIT } from "@/lib/anthropometry";

export async function GET() { const userId = await getAuthenticatedUserId(); if (!userId) return createUserUnauthorizedResponse(); try { return NextResponse.json(await prisma.bodyMeasurementEntry.findMany({ where: { userId }, orderBy: { measuredAt: "desc" } })); } catch (error) { console.error(error); return createInternalServerErrorResponse(); } }
export async function POST(request: Request) { const userId = await getAuthenticatedUserId(); if (!userId) return createUserUnauthorizedResponse(); let body: unknown; try { body = await request.json(); } catch { return createJsonErrorResponse("Invalid JSON payload.", 400); } const parsed = measurementSchema.safeParse(body); if (!parsed.success) return createJsonValidationErrorResponse("Invalid measurement entry.", parsed.error.flatten().fieldErrors); const isPro = hasProAccess(await getUserSubscription(userId)); const capabilityValidation = validateStoredMeasurementCapabilities(parsed.data as Record<string, unknown>, isPro); if (!capabilityValidation.success) return createJsonValidationErrorResponse("Some measurements require Pro.", Object.fromEntries(Object.entries(capabilityValidation.errors).map(([key, error]) => [key, [error]]))); try { const entry = await prisma.$transaction(async (tx) => { if (!isPro) { const count = await tx.bodyMeasurementEntry.count({ where: { userId } }); if (count >= FREE_MEASUREMENT_HISTORY_LIMIT) throw new FreeMeasurementLimitError(); } const created = await tx.bodyMeasurementEntry.create({ data: { userId, ...parsed.data } }); if (created.bodyweightKg) { const latest = await tx.bodyMeasurementEntry.findFirst({ where: { userId, bodyweightKg: { not: null } }, orderBy: { measuredAt: "desc" } }); if (latest?.id === created.id) await tx.user.update({ where: { id: userId }, data: { bodyweightKg: created.bodyweightKg.toNumber() } }); } return created; }); return NextResponse.json(entry, { status: 201 }); } catch (error) { if (error instanceof FreeMeasurementLimitError) return createJsonErrorResponse(`Free users can keep up to ${FREE_MEASUREMENT_HISTORY_LIMIT} measurement entries.`, 403); console.error(error); return createInternalServerErrorResponse(); } }
class FreeMeasurementLimitError extends Error {}
