import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { createInternalServerErrorResponse, createJsonErrorResponse, createJsonValidationErrorResponse } from "@/lib/api-response";
import { createUserUnauthorizedResponse, getAuthenticatedUserId } from "@/lib/user-auth";
import { serializeNutritionEntry } from "@/lib/nutrition/entry-serializer";
import { nutritionDate, nutritionEntryUpdateSchema, snapshotForFood } from "@/lib/nutrition/log";
const fields = ["caloriesKcal", "proteinGrams", "carbohydrateGrams", "fatGrams", "fiberGrams", "sugarGrams", "saturatedFatGrams", "sodiumMg", "saltGrams"] as const;
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { const userId = await getAuthenticatedUserId(); if (!userId) return createUserUnauthorizedResponse(); let body: unknown; try { body = await request.json(); } catch { return createJsonErrorResponse("Invalid JSON payload.", 400); } const parsed = nutritionEntryUpdateSchema.safeParse(body); if (!parsed.success) return createJsonValidationErrorResponse("Invalid nutrition entry.", parsed.error.flatten().fieldErrors); const { id } = await params; try { const entry = await prisma.nutritionEntrySnapshot.findFirst({ where: { id, userId }, include: { foodRevision: true } }); if (!entry) return createJsonErrorResponse("Nutrition entry not found.", 404); const grams = parsed.data.gramsConsumed ?? Number(entry.gramsConsumed); const revision = entry.foodRevision as unknown as Record<string, unknown>; const nutrition = snapshotForFood(Object.fromEntries(fields.map((key) => [key, revision[key] == null ? undefined : Number(revision[key])])), grams); await prisma.nutritionEntrySnapshot.update({ where: { id }, data: { ...(parsed.data.date ? { loggedFor: nutritionDate(parsed.data.date) } : {}), ...(parsed.data.mealCategory ? { mealCategory: parsed.data.mealCategory } : {}), ...(parsed.data.quantity ? { quantity: parsed.data.quantity } : {}), ...(parsed.data.unit ? { unit: parsed.data.unit } : {}), ...(parsed.data.gramsConsumed ? { gramsConsumed: grams, ...Object.fromEntries(fields.map((key) => [`${key}Snapshot`, nutrition[key] ?? null])) } : {}) } }); const updated = await prisma.nutritionEntrySnapshot.findUniqueOrThrow({ where: { id }, include: { food: { include: { aliases: { select: { name: true } }, details: { select: { categories: true, productImageUrl: true } } } } } }); return NextResponse.json(serializeNutritionEntry(updated)); } catch (error) { console.error("NUTRITION_LOG_UPDATE_FAILED", error); return createInternalServerErrorResponse(); } }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { const userId = await getAuthenticatedUserId(); if (!userId) return createUserUnauthorizedResponse(); const { id } = await params; const result = await prisma.nutritionEntrySnapshot.deleteMany({ where: { id, userId } }); if (!result.count) return createJsonErrorResponse("Nutrition entry not found.", 404); return NextResponse.json({ ok: true }); }
