"use client";

import Link from "next/link";
import Image from "next/image";
import { Copy, ExternalLink } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import type { getAdminUserInsight } from "@/lib/admin-user-insights";

type Insight = NonNullable<Awaited<ReturnType<typeof getAdminUserInsight>>>;
type Props = { insight: Insight };

function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Sofia" }).format(new Date(value)) : "Not recorded"; }
function metric(value: number) { return new Intl.NumberFormat("en", { maximumFractionDigits: 1 }).format(value); }
function planLabel(plan: Insight["user"]["plan"]) { return plan === "LIFETIME" ? "Lifetime" : plan === "PRO" ? "Pro" : "Free"; }
function DetailList({ children }: { children: React.ReactNode }) { return <div className="divide-y rounded-xl border">{children}</div>; }
function Empty({ children }: { children: React.ReactNode }) { return <Card><CardContent className="p-6 text-sm text-muted-foreground">{children}</CardContent></Card>; }

export function AdminUserInsight({ insight }: Props) {
  const { user, overview } = insight;
  const copyId = async () => { try { await navigator.clipboard.writeText(user.id); toast.success("User ID copied"); } catch { toast.error("Could not copy user ID."); } };
  const cards = [
    ["Workouts", user.workoutsCount], ["Total sets", overview.totalSets], ["Total reps", overview.totalReps], ["Nutrition entries", user.nutritionEntriesCount], ["Nutrition days · 30d", overview.nutritionDays30], ["AI scans", overview.aiScans], ["Describe uses", overview.describeUses], ["Barcode lookups", overview.barcodeLookups], ["Saved meals", overview.savedMeals], ["Supplements", overview.supplementsTracked], ["Parks submitted", user.parksCount], ["Food contributions", user.foodContributionsCount], ["Records", overview.records],
  ] as const;
  return <div className="space-y-6">
    <Card><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 gap-3"><div className="grid size-12 shrink-0 place-items-center overflow-hidden rounded-full bg-primary/10 font-semibold text-primary">{user.image ? <Image src={user.image} alt="" width={48} height={48} unoptimized className="size-full object-cover" /> : (user.name ?? user.email ?? "U").slice(0, 1).toUpperCase()}</div><div className="min-w-0"><h1 className="truncate text-2xl font-bold">{user.name ?? user.username ?? "Unnamed user"}</h1><p className="truncate text-sm text-muted-foreground">{user.email ?? "No email address"}</p><div className="mt-2 flex flex-wrap gap-2"><Badge variant={user.plan === "FREE" ? "secondary" : "default"}>{planLabel(user.plan)}</Badge><Badge variant="outline">Account role unavailable</Badge>{user.foodContributionsCount ? <Badge variant="outline">Contributor</Badge> : null}</div></div></div><div className="space-y-1 text-sm text-muted-foreground sm:text-right"><p>Joined {formatDate(user.joinedAt)}</p><p>Last active {formatDate(user.lastActiveAt)}</p><div className="flex items-center gap-1 sm:justify-end"><code className="max-w-48 truncate text-xs">{user.id}</code><Button size="icon-sm" variant="ghost" aria-label="Copy user ID" onClick={() => void copyId()}><Copy className="size-3.5" /></Button></div></div></CardContent></Card>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{cards.map(([label, value]) => <Card key={label}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold">{metric(value)}</p></CardContent></Card>)}</div>
    <Tabs defaultValue="overview" className="w-full"><div className="overflow-x-auto pb-1"><TabsList className="min-w-[720px]"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger><TabsTrigger value="workouts">Workouts</TabsTrigger><TabsTrigger value="nutrition">Nutrition</TabsTrigger><TabsTrigger value="ai">AI usage</TabsTrigger><TabsTrigger value="supplements">Supplements</TabsTrigger><TabsTrigger value="contributions">Contributions</TabsTrigger><TabsTrigger value="social">Social</TabsTrigger><TabsTrigger value="records">Records</TabsTrigger></TabsList></div>
      <TabsContent value="overview"><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><h2 className="font-semibold">Account</h2></CardHeader><CardContent className="space-y-2 text-sm"><p><span className="text-muted-foreground">Subscription:</span> {user.subscription ? `${planLabel(user.plan)} · ${user.subscription.status.toLowerCase()}` : "Free"}</p>{user.subscription?.currentPeriodEnd ? <p><span className="text-muted-foreground">Period ends:</span> {formatDate(user.subscription.currentPeriodEnd)}{user.subscription.cancelAtPeriodEnd ? " · cancelling" : ""}</p> : null}<p><span className="text-muted-foreground">Average nutrition · 7d:</span> {Math.round(overview.averageCalories7)} kcal · {metric(overview.averageProtein7)} g protein</p><p className="text-xs text-muted-foreground">Last active is a throttled account-presence heartbeat, not click tracking. Barcode camera scans are not retained; only future server-side lookup telemetry could be shown.</p></CardContent></Card><Card><CardHeader><h2 className="font-semibold">Recent activity</h2></CardHeader><CardContent className="space-y-3">{insight.timeline.slice(0, 5).map((event) => <div key={event.id}><p className="text-sm font-medium">{event.title}</p><p className="text-xs text-muted-foreground">{event.detail ?? ""} · {formatDate(event.createdAt)}</p></div>)}{insight.timeline.length === 0 ? <p className="text-sm text-muted-foreground">No persisted product activity yet.</p> : null}</CardContent></Card></div></TabsContent>
      <TabsContent value="activity">{insight.timeline.length ? <DetailList>{insight.timeline.map((event) => <div className="p-4" key={event.id}><div className="flex flex-wrap items-baseline justify-between gap-2"><p className="font-medium">{event.title}</p><time className="text-xs text-muted-foreground">{formatDate(event.createdAt)}</time></div>{event.detail ? <p className="mt-1 text-sm text-muted-foreground">{event.detail}</p> : null}</div>)}</DetailList> : <Empty>Timeline events are derived from persisted workouts, nutrition, AI counters, supplements, contributions, follows, and records. No raw prompts or photos are retained here.</Empty>}</TabsContent>
      <TabsContent value="workouts">{insight.workouts.length ? <DetailList>{insight.workouts.map((workout) => <div className="p-4" key={workout.id}><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium">{workout.title}</p><p className="text-sm text-muted-foreground">{workout.exerciseNames.join(" · ") || "No exercises"}</p></div><Badge variant="outline">{workout.visibility.toLowerCase()}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{formatDate(workout.completedAt ?? workout.startedAt)} · {workout.sets} sets · {Math.round(workout.volume).toLocaleString()} kg volume · {workout.records} PRs</p><Button asChild variant="link" className="mt-1 h-auto px-0"><Link href={`/workouts/${workout.id}`}>Open workout <ExternalLink className="ml-1 size-3" /></Link></Button></div>)}</DetailList> : <Empty>No workouts recorded.</Empty>}</TabsContent>
      <TabsContent value="nutrition">{insight.nutrition.length ? <DetailList>{insight.nutrition.map((entry) => <div className="flex flex-wrap items-center justify-between gap-3 p-4" key={entry.id}><div><p className="font-medium">{entry.foodNameSnapshot}</p><p className="text-sm text-muted-foreground">{entry.mealCategory.toLowerCase()} · {entry.gramsConsumed} g · {entry.sourceSnapshot}</p></div><div className="text-right text-sm"><p>{Math.round(entry.caloriesKcalSnapshot)} kcal</p><p className="text-muted-foreground">P {metric(entry.proteinGramsSnapshot)} · C {metric(entry.carbohydrateGramsSnapshot)} · F {metric(entry.fatGramsSnapshot)}</p><time className="text-xs text-muted-foreground">{formatDate(entry.loggedFor)}</time></div></div>)}</DetailList> : <Empty>No immutable nutrition snapshots recorded.</Empty>}</TabsContent>
      <TabsContent value="ai">{insight.aiUsage.length ? <DetailList>{insight.aiUsage.map((day) => <div className="flex justify-between gap-3 p-4" key={day.date}><p className="font-medium">{formatDate(day.date)}</p><p className="text-sm text-muted-foreground">AI Scan {day.aiScanCount} · Describe {day.describeCount}</p></div>)}</DetailList> : <Empty>AI usage is stored as daily request counters only. Raw meal images, prompts, and descriptions are intentionally not shown.</Empty>}<p className="mt-3 text-xs text-muted-foreground">Barcode lookup telemetry: {overview.barcodeLookups} server lookup{overview.barcodeLookups === 1 ? "" : "s"}. Camera frames and barcode values are never stored.</p></TabsContent>
      <TabsContent value="supplements">{insight.supplements.plans.length ? <div className="space-y-4"><DetailList>{insight.supplements.plans.map((plan) => <div className="flex justify-between gap-3 p-4" key={plan.id}><div><p className="font-medium">{plan.name}</p><p className="text-sm text-muted-foreground">{plan.frequency.toLowerCase().replaceAll("_", " ")}{plan.preferredTime ? ` · ${plan.preferredTime.toLowerCase().replaceAll("_", " ")}` : ""}</p></div><Badge variant={plan.isActive ? "default" : "secondary"}>{plan.isActive ? "Active" : "Archived"}</Badge></div>)}</DetailList><Card><CardHeader><h2 className="font-semibold">Recent doses</h2></CardHeader><CardContent className="space-y-2">{insight.supplements.logs.length ? insight.supplements.logs.map((log) => <p className="text-sm" key={log.id}>{log.name} <span className="text-muted-foreground">· {formatDate(log.completedAt)}</span></p>) : <p className="text-sm text-muted-foreground">No dose logs.</p>}</CardContent></Card></div> : <Empty>No supplement plans recorded.</Empty>}</TabsContent>
      <TabsContent value="contributions"><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><h2 className="font-semibold">Food contributions</h2></CardHeader><CardContent className="space-y-3">{insight.contributions.foods.map((food) => <div key={food.id}><p className="font-medium">{food.name} <Badge variant="outline">{food.contributionStatus ?? "PENDING"}</Badge></p><p className="text-xs text-muted-foreground">Submitted {formatDate(food.createdAt)}{food.reviewedAt ? ` · reviewed ${formatDate(food.reviewedAt)}` : ""}</p></div>)}{insight.contributions.foods.length === 0 ? <p className="text-sm text-muted-foreground">No food contributions.</p> : null}</CardContent></Card><Card><CardHeader><h2 className="font-semibold">Park submissions</h2></CardHeader><CardContent className="space-y-3">{insight.contributions.parks.map((park) => <div key={park.id}><p className="font-medium">{park.name} <Badge variant="outline">{park.submissionStatus}</Badge></p><p className="text-xs text-muted-foreground">Submitted {formatDate(park.createdAt)}{park.reviewedAt ? ` · reviewed ${formatDate(park.reviewedAt)}` : ""}</p></div>)}{insight.contributions.parks.length === 0 ? <p className="text-sm text-muted-foreground">No park submissions.</p> : null}</CardContent></Card></div></TabsContent>
      <TabsContent value="social"><Card><CardContent className="grid gap-4 p-5 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Followers</p><p className="text-2xl font-bold">{overview.followers}</p></div><div><p className="text-xs text-muted-foreground">Following</p><p className="text-2xl font-bold">{overview.following}</p></div></CardContent></Card>{insight.social.follows.length ? <DetailList>{insight.social.follows.map((follow) => <div className="flex justify-between gap-3 p-4" key={follow.id}><p>Followed {follow.name}</p><time className="text-sm text-muted-foreground">{formatDate(follow.createdAt)}</time></div>)}</DetailList> : <p className="mt-4 text-sm text-muted-foreground">No persisted follows. Profile views and clicks are not tracked.</p>}</TabsContent>
      <TabsContent value="records">{insight.records.length ? <DetailList>{insight.records.map((record) => <div className="flex flex-wrap justify-between gap-3 p-4" key={record.id}><div><p className="font-medium">{record.exercise}</p><p className="text-sm text-muted-foreground">{record.type.replaceAll("_", " ")} · {record.workout.title}</p></div><div className="text-right"><p className="font-semibold">{record.value}</p><time className="text-xs text-muted-foreground">{formatDate(record.achievedAt)}</time></div></div>)}</DetailList> : <Empty>No personal records recorded.</Empty>}</TabsContent>
    </Tabs>
  </div>;
}
