"use client";

import Image from "next/image";
import { useRef, useState } from "react";
import { ImagePlus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { WORKOUT_PHOTO_ACCEPT, WORKOUT_PHOTO_MAX_COUNT, WORKOUT_PHOTO_MAX_EDGE, WORKOUT_PHOTO_WEBP_QUALITY } from "@/lib/workout-photo";

export function WorkoutCompletionPhotoDialog({ workoutId, open, onContinue }: { workoutId: number | null; open: boolean; onContinue: () => void }) {
  const input = useRef<HTMLInputElement>(null); const [files, setFiles] = useState<File[]>([]); const [uploading, setUploading] = useState(false); const [error, setError] = useState<string | null>(null);
  function select(next: FileList | null) { if (!next) return; setError(null); const selected = Array.from(next); if (process.env.NODE_ENV === "development") console.info("Workout photo selection", { workoutId, count: selected.length, files: selected.map(({ name, type, size }) => ({ name, type, size })) }); setFiles((current) => [...current, ...selected].slice(0, WORKOUT_PHOTO_MAX_COUNT)); }
  async function upload() { if (!workoutId || !files.length) return onContinue(); setUploading(true); setError(null); try { const { default: compress } = await import("browser-image-compression"); for (const original of files) { const compressed = await compress(original, { maxWidthOrHeight: WORKOUT_PHOTO_MAX_EDGE, initialQuality: WORKOUT_PHOTO_WEBP_QUALITY, fileType: "image/webp", useWebWorker: true, preserveExif: false }); const uploadFile = new File([compressed], `${original.name.replace(/\.[^.]+$/, "")}.webp`, { type: "image/webp" }); if (process.env.NODE_ENV === "development") console.info("Workout photo compressed", { workoutId, originalBytes: original.size, compressedBytes: uploadFile.size, type: uploadFile.type }); const form = new FormData(); form.set("file", uploadFile); const response = await fetch(`/api/user/workouts/${workoutId}/photos`, { method: "POST", body: form }); const payload = await response.json().catch(() => null); if (process.env.NODE_ENV === "development") console.info("Workout photo upload response", { workoutId, status: response.status, storageKey: payload?.photo?.storageKey }); if (!response.ok) throw new Error(payload?.error ?? "Unable to upload photo."); } onContinue(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to upload photos."); } finally { setUploading(false); } }
  return <Dialog open={open} onOpenChange={(next) => { if (!next && !uploading) onContinue(); }}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>Workout completed 🎉</DialogTitle><DialogDescription>Add a few photos now, or manage them later from the completed workout.</DialogDescription></DialogHeader><input ref={input} type="file" accept={WORKOUT_PHOTO_ACCEPT} multiple className="sr-only" onChange={(event) => select(event.target.files)} />{files.length ? <div className="grid grid-cols-3 gap-2">{files.map((file, index) => <div key={`${file.name}-${index}`} className="relative aspect-square overflow-hidden rounded-md border"><Image src={URL.createObjectURL(file)} alt="Selected workout photo" fill sizes="120px" className="object-cover"/><Button type="button" size="icon-sm" variant="secondary" className="absolute right-1 top-1" aria-label="Remove selected photo" onClick={() => setFiles((items) => items.filter((_, itemIndex) => itemIndex !== index))}><Trash2 /></Button></div>)}</div> : null}{error ? <p className="text-sm text-destructive" role="alert">{error}</p> : null}<DialogFooter className="gap-2 sm:gap-0"><Button type="button" variant="outline" disabled={uploading || files.length >= WORKOUT_PHOTO_MAX_COUNT} onClick={() => input.current?.click()}><ImagePlus /> Upload photos</Button><Button type="button" variant="ghost" disabled={uploading} onClick={onContinue}>Skip</Button><Button type="button" disabled={uploading || !files.length} onClick={() => void upload()}>{uploading ? "Uploading…" : "Upload and continue"}</Button></DialogFooter></DialogContent></Dialog>;
}
