"use client";

import Image from "next/image";
import { useRef, useState } from "react";
import { ImagePlus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { WORKOUT_PHOTO_ACCEPT, WORKOUT_PHOTO_MAX_COUNT, WORKOUT_PHOTO_MAX_EDGE, WORKOUT_PHOTO_WEBP_QUALITY } from "@/lib/workout-photo";

type Photo = { id: string; url: string; width: number; height: number };

export function WorkoutPhotoManager({ workoutId, initialPhotos }: { workoutId: number; initialPhotos: Photo[] }) {
  const [photos, setPhotos] = useState(initialPhotos); const [pending, setPending] = useState<File[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [open, setOpen] = useState<string | null>(null); const input = useRef<HTMLInputElement>(null);
  async function add(files: FileList | null) { if (!files) return; setError(null); const room = WORKOUT_PHOTO_MAX_COUNT - photos.length - pending.length; const selected = Array.from(files).slice(0, room); if (selected.length < files.length) setError("A workout can have up to 10 photos."); setPending((current) => [...current, ...selected]); }
  async function save() { setSaving(true); setError(null); try { const { default: compress } = await import("browser-image-compression"); const uploaded: Photo[] = []; for (const source of pending) { const compressed = await compress(source, { maxWidthOrHeight: WORKOUT_PHOTO_MAX_EDGE, initialQuality: WORKOUT_PHOTO_WEBP_QUALITY, fileType: "image/webp", useWebWorker: true, preserveExif: false }); const file = new File([compressed], `${source.name.replace(/\.[^.]+$/, "")}.webp`, { type: "image/webp" }); const form = new FormData(); form.set("file", file); const response = await fetch(`/api/user/workouts/${workoutId}/photos`, { method: "POST", body: form }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Unable to upload photo."); uploaded.push({ id: payload.photo.id, url: URL.createObjectURL(file), width: payload.photo.width, height: payload.photo.height }); } setPhotos((current) => [...current, ...uploaded]); setPending([]); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to upload photos."); } finally { setSaving(false); } }
  async function remove(photo: Photo) { setError(null); const response = await fetch(`/api/user/workouts/${workoutId}/photos/${photo.id}`, { method: "DELETE" }); if (!response.ok) { const payload = await response.json().catch(() => null); setError(payload?.error ?? "Unable to delete photo."); return; } setPhotos((current) => current.filter((item) => item.id !== photo.id)); }
  return <Card className="mb-6"><CardHeader><CardTitle className="text-lg">Workout photos</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{photos.map((photo) => <div key={photo.id} className="group relative aspect-square overflow-hidden rounded-lg border"><Image src={photo.url} alt="Workout photo" fill sizes="(max-width: 640px) 45vw, 220px" className="object-cover" onClick={() => setOpen(photo.url)} /><Button type="button" size="icon-sm" variant="destructive" className="absolute right-1 top-1" aria-label="Delete workout photo" onClick={() => void remove(photo)}><Trash2 /></Button></div>)}{pending.map((photo, index) => <div key={`${photo.name}-${index}`} className="relative aspect-square overflow-hidden rounded-lg border"><Image src={URL.createObjectURL(photo)} alt="Selected workout photo" fill sizes="(max-width: 640px) 45vw, 220px" className="object-cover"/><Button type="button" size="icon-sm" variant="secondary" className="absolute right-1 top-1" aria-label="Remove selected photo" onClick={() => setPending((items) => items.filter((_, itemIndex) => itemIndex !== index))}><Trash2 /></Button></div>)}</div><input ref={input} className="sr-only" type="file" accept={WORKOUT_PHOTO_ACCEPT} multiple onChange={(event) => void add(event.target.files)} /><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={saving || photos.length + pending.length >= WORKOUT_PHOTO_MAX_COUNT} onClick={() => input.current?.click()}><ImagePlus /> Upload photos</Button>{pending.length ? <Button type="button" disabled={saving} onClick={() => void save()}>{saving ? "Uploading…" : `Upload ${pending.length} photo${pending.length === 1 ? "" : "s"}`}</Button> : null}</div><p className="text-xs text-muted-foreground">JPEG, PNG, WebP, HEIC, or HEIF · up to 10 photos · compressed to WebP before upload.</p>{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}</CardContent><Dialog open={Boolean(open)} onOpenChange={(value) => !value && setOpen(null)}><DialogContent className="max-w-4xl p-2"><Image src={open ?? "/icons/icon.png"} alt="Workout photo" width={1600} height={1200} unoptimized className="max-h-[80dvh] w-full rounded-lg object-contain" /></DialogContent></Dialog></Card>;
}
